### ISSUE TITLE
Add Related Events Feature

### ISSUE THREAD

**Issue by mzagaja** [MAPC/digitalhub#131]
**Describe the feature. What should a user be able to do?**
As a user, when I see an event, I would also like to see events related to my current event.

**Why do we need this feature?**
If the event is not at a time or place that I can get to, I would like to when similar events are so I can get there.

![image](https://user-images.githubusercontent.com/565647/46967800-92602a80-d07f-11e8-9281-403d73e3f946.png)

**Comment by theryankelly** [comment]
Close.  Effort to complete too high. Will use text and type to group events.
