### ISSUE TITLE
Enable "Find Out", "Weigh In" and "Events" Buttons on Home Page

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#169]
**Describe the feature. What should a user be able to do?**
"Find Out", "Weigh In" and "Events" square buttons should be enabled on home page. The user should be able to navigate to those pages from these buttons. The style should match the 2.0xd file, images to follow.

*Why do we need this feature?**
To allow for navigation to featured areas.

**Alternatives**
Style of buttons may change in future releases.

**Comment by mzagaja** [comment]
Buttons need to be enabled via feature flag in the console. Currently done on staging.
```
require 'flipper/adapters/active_record'
adapter = Flipper::Adapters::ActiveRecord.new
flipper[:action_buttons].enable
```
Then will need to update hardcoded URLs that these buttons point to be the correct URLs based on what the CMS generates for those pages. Once the design is available then can start customizing the view templates and making them available.

**Comment by mzagaja** [comment]
This is resolved.
