### ISSUE TITLE
Add Video to Home Page

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#170]
**Describe the feature. What should a user be able to do?**
MetroCommon video should be embedded and viewable on home page. Style and placement to match 2.0xd images to follow. User should be able to watch the embedded video on the page.

**Why do we need this feature?**
Need a prominent home for this featured piece of content.

**Comment by mzagaja** [comment]
Currently blocked by the need for whomever has the video file and access to the MAPC YouTube channel to upload it. Once we have the url it can be added to the home page.

**Comment by mzagaja** [comment]
This is done.
