### ISSUE TITLE
Find Out Page Redesign

### ISSUE THREAD

**Issue by Kit-Un** [MAPC/digitalhub#192]
Technical changes needed
i.e indentation/clearer headings

- Hold for XD File

**Comment by theryankelly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wireframe for Find Out](https://trello.com/c/oRKULJcd/4-wireframe-for-find-out)

**Comment by theryankelly** [comment]
032119 Digital Hub XD file contains new Find Out Design
