### ISSUE TITLE
Missing Text Wrap/Image Resize

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#202]
**Describe the bug**
The text under the video on the home page and image on the Phase 1 of Process Details are not wrapping when screen width is reduced to mobile size.  Those were the only two cases I could find where content was not adjusting correctly to the width.

**Expected behavior**
The text should wrap as width decreases.  Image should rescale to fit the width.

**Screenshots**
![screen shot 2019-02-08 at 11 01 37 am](https://user-images.githubusercontent.com/2421382/52491113-51db6e00-2b94-11e9-8af4-5c81eebcc4fc.png)
![screen shot 2019-02-08 at 11 01 58 am](https://user-images.githubusercontent.com/2421382/52491114-51db6e00-2b94-11e9-81a4-2dbb5f38f4a5.png)

**Additional context**
Investment in a testing platform may address this issue in the future.

**Comment by mzagaja** [comment]
The reason the front page text is not wrapping is a user explicitly set height and width attributes of the table and td tags in the refinery admin. I removed the explicit height and width attributes from the DOM tags in the CMS and it appears to have fixed this.

![image](https://user-images.githubusercontent.com/565647/52498567-2b72fe00-2ba7-11e9-882d-6846f764d1d2.png)

PR coming with a style update to fix the image, just needs a width attribute of 100%.
