### ISSUE TITLE
New Announcements Element

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#224]
**Describe the feature. What should a user be able to do?**
This section of the home page should include a carousel and text block.  The two should rotate together through "announcements".  

- At smaller screen sizes we should go to a 2x2 block and adjust the image block demsoins to fit.  
- The announcement text and image with need to be edited through the CMS admin interface.  
- On hover the rotation of announcements should cease. 
- Should align with other elements in this section.

From 3.0 XD file:
![screen shot 2019-03-06 at 4 45 45 pm](https://user-images.githubusercontent.com/2421382/53916193-832e4900-402f-11e9-88ec-5a275c3ffd01.png)

**Why do we need this feature?**
This is needed as part of the Phase 2 update to align with other style changes.

**Alternatives**
@Kit-Un the navigation bar of the announcements could be expanded or changes to better link the two (text and image)

**Comment by mzagaja** [comment]
I need the content for items 3 and 4 to finish this one out. Or I can delete those and just have 1 and 2.
