### ISSUE TITLE
Object.create missing in IE11

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/digitalhub#230]
Andre was having issues loading website in IE11 on his machine (this issue doesn't reproduce in Citrix). The error that was being consoled was `Object.create is undefined`. We need to supply an `Object.create` shim for versions of IE.

**Comment by mzagaja** [comment]
There is currently no `Object.create()` in the code base and current IE users can load the site, so this was presumably fixed at some point. Closing this issue as stale.
