### ISSUE TITLE
Hero Image Rotation

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#237]
**Describe the feature. What should a user be able to do?**
The goal is to have different images rotate in the hero of the home page.  

- Hero images can be found here: Public/MetroCommon 2050/02 Integrated Communications/05 Digital Hub/assets/Hero Slider.  
- The pace of rotate should be slower than any other carousels on the home page.  
- The admin interface should be able to control upload and management of images
-  Images should auto-resize when uploaded

**Why do we need this feature?**
This is needed to drive action and keep content fresh.

**Alternatives**
A video could be used in place of rotating images

**Additional context**
Examples:
![Screen Shot 2019-03-19 at 10 08 31 AM](https://user-images.githubusercontent.com/2421382/54612310-15bae900-4a2f-11e9-976d-ac46ef2d1840.png)
![Screen Shot 2019-03-19 at 10 06 29 AM](https://user-images.githubusercontent.com/2421382/54612311-16537f80-4a2f-11e9-8794-8702c7f3b173.png)
![Screen Shot 2019-03-19 at 10 04 44 AM](https://user-images.githubusercontent.com/2421382/54612312-16537f80-4a2f-11e9-88e2-e6936311bdd9.png)

**Comment by smithWEBtek** [comment]
I have this working temporarily using JSON data from the announcements in Refinery. 
Once we have a JSON endpoint for images, I can refactor to point that source.

**Comment by smithWEBtek** [comment]
@theryankelly I have combined this with issue #245, where I believe I have both issues solved (#1 the Refinery admin extension for hero images and #2 the hero image rotation).  Depends on Matt's review of course.
