### ISSUE TITLE
Find Out Filter

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#293]
**Describe the feature. What should a user be able to do?**
The user should be able to filter the published content of the Digital Hub.  The filter will have two levels of filtering functionality, by "type" and by "topic areas".  It's intended that these will be done with tags.  The tags may change through the regional planning process.  Both filters will be part of a sentence with text to select.  

> You're looking for _everything_
> in _all topic areas_.

  **Content Types**
  - everything 
  - publications
  - news
  - events
  - calls to action
  - datasets

  **Topic Areas**
  - all topic areas
  - transportation
  - housing
  - environment
  - health
  - economic Development
  - arts & culture
  - dynamic government

**Why do we need this feature?**
This feature is needed to filter the content of the regional planning process.

**Comment by smithWEBtek** [comment]
This issue has been reduced to the functionality only, with the design/style separated into issue #294. 

This issue was addressed with the merging of 
Merge pull request #339 from MAPC/bjs/332-tag-database-model-change-v2
on 7/8/2019
