### ISSUE TITLE
Find Out Filter - Styling and UX

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#352]
This issue is closely related to: #294 and should be addressed within the same Pull Request when ready.

If a filter is selected it remains till changed. Meaning one filter does not clear another filter. content displayed will be only that which applies to both filter selections.

The filter should enable a dropdown menu and background overlay when any of the "select text" is selected. When new select text is chosen the overlay disappears and a filter is triggered. It's expected that the menu and overlay could be canceled at any time by clicking on the overlay and the previous selection being retained.
![ss1](https://user-images.githubusercontent.com/16054332/61960655-dcbdf280-af93-11e9-9159-8c936fd1fbc7.png)

The filter will live in the header. To match the XD 3.0 the header should be the same size as the Weigh In header when no selections have been made. The size of the header should expand when a "topic area" is selected. A narrative section for the "topic area" should then appear. The content should still filter dynamically based on the "type" filter and switch to different "topic area" if selected.
![ss2](https://user-images.githubusercontent.com/16054332/61960662-e0ea1000-af93-11e9-981d-3e8bb935ceee.png)

Alternatives
We may have to scrap the "topic area" narrative sections is development cost is too high.

When selecting content we may want to adjust how the filter is animated.

Why do we need this feature?
This feature is need to filter the content of the regional planning process.

**Comment by theryankelly** [comment]
Issue presenting on different browsers. May need to reconsider what we are using for dropdown. Our inspiration works on all browsers: https://bouguessa.com/shop

Chrome on Windows (Version 75.0.3770.142) white on white 
![Screen Shot 2019-08-06 at 1 32 04 PM](https://user-images.githubusercontent.com/2421382/62562213-baa75880-b84e-11e9-962a-6120547f4de8.png)

IE on Windows (Version 11.0.9600.19356) multiple issues
![Screen Shot 2019-08-06 at 1 30 15 PM](https://user-images.githubusercontent.com/2421382/62562214-baa75880-b84e-11e9-8521-eb391adfee8b.png)
![Screen Shot 2019-08-06 at 1 30 25 PM](https://user-images.githubusercontent.com/2421382/62562216-baa75880-b84e-11e9-9e81-a1f54d4228cb.png)
![Screen Shot 2019-08-06 at 1 30 44 PM](https://user-images.githubusercontent.com/2421382/62562217-baa75880-b84e-11e9-8d88-71143fdf4268.png)

Safari 12.1.2 (14607.3.9) no overlay
![Screen Shot 2019-08-06 at 1 23 49 PM](https://user-images.githubusercontent.com/2421382/62562218-baa75880-b84e-11e9-8541-48b664fb1bca.png)

Firefox on Mac (66.0.3) green text and white drop down
![Screen Shot 2019-08-06 at 1 35 54 PM](https://user-images.githubusercontent.com/2421382/62562436-2689c100-b84f-11e9-8872-0d65403ec85e.png)

Chrome on Mac (Version 75.0.3770.142) overlay does not go away on click
![Screen Shot 2019-08-06 at 1 38 11 PM](https://user-images.githubusercontent.com/2421382/62562602-7b2d3c00-b84f-11e9-9b9d-650d8e45ba80.png)
![Screen Shot 2019-08-06 at 1 23 56 PM](https://user-images.githubusercontent.com/2421382/62562219-bb3fef00-b84e-11e9-8044-a3d78876fa19.png)
