### ISSUE TITLE
Content Update Error

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#361]
**Describe the bug**
When updating the text of the "Community Engagement Mini Grant Opportunity" Kit and I are both unable to save new edits.  We receive the error:

<img width="620" alt="Screen Shot 2019-07-30 at 1 56 43 PM" src="https://user-images.githubusercontent.com/2421382/62153181-02b7ff80-b2d2-11e9-967e-5bd4f0cfa8e6.png">

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Login to hub admin
2. go to https://metrocommon.mapc.org/hubadmin/announcements/2
3. add text
4. click save
5. See error

**Expected behavior**
Need to be able to update and save pages without recreating

**Context**
Could this have to do with requirement for tags, but production not having all the PRs related to tags?

**Comment by smithWEBtek** [comment]
This issue is solved through #374 and the 2 reversions done prior to it. After pushing master to production, I was able to create, edit and delete an Announcement and an Event.
