### ISSUE TITLE
Change Browser Title

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#362]
The browser tab title shows as "Taggings - Metropolitan Area Planning Council"

![fix-find-out-title](https://user-images.githubusercontent.com/16054332/62154238-59bed400-b2d4-11e9-9700-212ca5311167.png)

It should be changed to:  "Find Out - MetroCommon 2050"

**Comment by atomtay** [comment]
I'm admittedly a bit confused as to how this happened in the first place; I did some experimenting in the Refinery admin and it looks like the page title is pulled from the Title text field and appended to " - MetroCommon 2050." I couldn't find the page in my local admin and thought it might have just been created directly within the repo, but I can't find it there either.

**Comment by mzagaja** [comment]
@atomtay When I played with this while reviewing the PR I discovered that `vendor/extensions/taggings/app/controllers/refinery/taggings/taggings_controller.rb` has a findout route that simply renders `refiner/pages/find_out.html` which is a template in app/views/refinery/pages/find_out.html.erb`. I think the title is just inherited as the default title for the application.html.erb associated with Refinery in the Refinery gem. 

@smithWEBtek A new idea to try now that I looked at this: The "find-out" route is actually a taggings index. So you should be able to refactor the find-out template under pages into the view template `vendor/extensions/taggings/app/views/refinery/taggings/index.html.erb` and add the following block with the title:

```
<% content_for :body_content_title do %>
  MetroCommon 2050
<% end %>
```
then finally update routes.rb to point `/find-out` to refinery's `taggings#index` route.

**Comment by smithWEBtek** [comment]
@mzagaja @atomtay that is great news! 

Agreed, the find_out page is functioning more like a taggings index page.
After making the changes suggested, the `:body_content_title` was not working, and with some experimentation, this code worked for the title block: 

```
<% content_for :title do %>
  MetroCommon 2050
<% end %>
```
**Note to self:  We will need to code the `Find Out` link into the menu, which was an issue anyway because it required creating a Find Out page manually in hubadmin. This is a requirement in issue #370 Side Bar Menu**
