### ISSUE TITLE
Site Bar Menu

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#370]
- Scrolling: when the site_bar menu comes out, vertical page scrolling is currently disabled.
- Expected behavior:  Main page is able to scroll regardless of the state of the  site_bar menu
- Script the creation of Find Out link, (without having to manually create a new page, choose a template and set as 'visible' in hub admin). 

All pages should have the menu overlay with scroll ability for main page area
Menu cancel either by X in the upper right, or by clicking anywhere on the white menu background.

Menu has the following links, in this order:

- Home (via hubadmin show/hide checkbox)
- Find Out (via jquery script)
- Voices From the Region (via jquery script)
- Process Details (via jquery script)
- Goals (via jquery script)

**Comment by theryankelly** [comment]
Weigh In is currently: https://metrocommon.mapc.org/stories/new should be https://metrocommon.mapc.org/stories

**Comment by theryankelly** [comment]
I imagine the site Menu will look like:

- Home
- Find Out
- Voice From the Region
- Process Details
- Goals

After work on search is completed in future projects, we may want to add Search to menu in some distinguishing way.  Until then we should leave off the menu.  I also see the Goals being removed from menu in future phases, this should be controlled by the checkbox in the admin.
