### ISSUE TITLE
Remove Card Gray Outline

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#371]
Remove Gray outline of boxes.

* There is a slight gray border around the images. 
* Ideally, we want to remove it. 
* However, it might be a side effect of using the CSS property `object-fit: cover;` to fill the space with the image while keeping its aspect ratio.

**Comment by mzagaja** [comment]
Which page does this present on? I do not see it in the one boxes.

**Comment by smithWEBtek** [comment]
This presents on `/find-out` page. 
Note, the border around Next Three Events is by design. 

This issue is regarding the border of the images on the display cards.

**Comment by mzagaja** [comment]
I cannot reproduce this locally:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/565647/63123151-5d11bb00-bf76-11e9-93d8-1f3a8505da6c.png">

Maybe the gray outline is from the specific images you used?

**Comment by smithWEBtek** [comment]
Yes, this is only noticeable on certain images with very light colors that bleed to the edge. Comparing two of them here: 
![image-borders](https://user-images.githubusercontent.com/16054332/63168045-0dc49c80-c001-11e9-93b1-d1e3bb8d9d8f.png)

**Comment by smithWEBtek** [comment]
Closing this one per @theryankelly request.
