### ISSUE TITLE
Upcoming Events Feature Broke

### ISSUE THREAD

**Issue by mzagaja** [MAPC/digitalhub#430]
**Describe the bug**
This test, or the feature associated with the test appears to have broken.

**Steps to reproduce**
1. `rspec ./spec/requests/findout_filter_spec.rb:95`

**Expected behavior**
The test will pass.

**Additional context**
45181c9ad61b52165293f81593e73bdf3ff67d2f is the first bad commit per 

`git bisect run bundle exec rspec ./spec/requests/findout_filter_spec.rb:95`

**Comment by smithWEBtek** [comment]
Resolved with #429
