### ISSUE TITLE
Clarify Past vs Future Events

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#463]
**Describe the feature. What should a user be able to do?**
We distinguish events between past and present on event page https://metrocommon.mapc.org/events

We should consider denoting past and future on the Find-Out page as well.  We could accomplish this in the "EVENT" subtitle with change to "PAST EVENT", "UPCOMING EVENT"

**Alternatives**
We could also put date in the the subtitle

![Screen Shot 2020-01-22 at 4 53 05 PM](https://user-images.githubusercontent.com/2421382/72938034-4008c180-3d38-11ea-9d32-b4d1e4ba33a0.png)

**Comment by theryankelly** [comment]
Example: 

![Screen Shot 2020-01-23 at 4 03 29 PM](https://user-images.githubusercontent.com/2421382/73023694-11ebb600-3dfa-11ea-9c33-5d0271e1ab4f.png)

**Comment by mzagaja** [comment]
Resolved in https://github.com/MAPC/digitalhub/pull/465
