### ISSUE TITLE
Diversity Deficit report not mobile responsive

### ISSUE THREAD

**Issue by TimReardon** [MAPC/digitalhub#506]
**Describe the bug**
Diversity Deficit report is not mobile responsive.  Text and images do not resize to fit smaller screen. Text runs off right side of screen.  Can't resize to fit all text on screen

**Steps to reproduce**

1. Go to https://metrocommon.mapc.org/reports/14 using a mobile phone
2. try to read it.   

**Expected behavior**
text and images should have resized to fit on screen

**Smartphone (please complete the following information):**
 - Device: iphone SE
 - OS: iOS 13.5.1
 - Browser: Chrome
 - Version 83.0.4103.88

**Additional context**
Jessie also reported this problem

**Comment by mzagaja** [comment]
Resolved by @atomtay fixing the content styling.

[Slack thread](https://mapc.slack.com/archives/C146M1XNK/p1594737302014900).

![image](https://user-images.githubusercontent.com/565647/88712014-11a0e000-d0e7-11ea-9871-2773b96e8f3e.png)
