### ISSUE TITLE
Edit About Page Section of Home Page

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#529]
The current design similar to Home Page Research section and will need a two-column format, external links, and dynamic background.

![image](https://user-images.githubusercontent.com/2421382/125675157-76de2106-2782-4f05-b24e-538c5483feb4.png)

**Comment by theryankelly** [comment]
Similar issue as to #527 section, need to appropriately use triangles to denote links or chose new icon.

**Comment by theryankelly** [comment]
Current Staging:
![image](https://user-images.githubusercontent.com/2421382/142912024-43ba4d79-0c0b-4ca8-b781-600b03122692.png)

Are these the links we want to include?
READ THE PLAN
METROCOMMON PROCESS
COMMUNITY OUTREACH AND INPUT
ACKNOWLEDGEMENTS
ABOUT MAPC

- Currently Process, Acknowledgements and About will all link to the same page, but different sections of that page. Good?
- Also are we good with COMMUNITY OUTREACH AND INPUT link out to the [Pory page](https://mc2050.pory.app/))? How do we want to handle questions about outreach page: #539 

@elisemaeharmon @sashaparodi

**Comment by theryankelly** [comment]
Working and links should be:

- Read The Plan - link to overview
- About the Plan - link to about-the-plan

![image](https://user-images.githubusercontent.com/2421382/146410836-58c160f0-f715-4e0f-aa17-867501dec956.png)

**Comment by trust-kimberly** [comment]
Reflected on staging (and currently being pushed to prod):

<img width="972" alt="Screen Shot 2021-12-16 at 2 01 44 PM" src="https://user-images.githubusercontent.com/62153141/146432583-df4d75ca-80e1-4f79-814f-5bbda5c2db1a.png">
