### ISSUE TITLE
Letter from Executive Director

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#535]
Intro letter from executive director
![image](https://user-images.githubusercontent.com/2421382/131170915-c70a6310-bf5f-4430-a09a-c587c412d083.png)

- [x] Decision needed on location
- Have as a pop-up model on home page
- Have as a pop-up model on report
- Have as a link in top of the report

**Comment by theryankelly** [comment]
Will have as a pop-up model on report page #537

**Comment by trust-kimberly** [comment]
Pop up model on Overview:
![Screen Shot 2021-10-29 at 2 26 26 PM](https://user-images.githubusercontent.com/62153141/139486487-2f4e82c6-5b81-497b-b014-a244f92f135f.png)

Pop up model on home page:
![Screen Shot 2021-10-29 at 2 44 23 PM](https://user-images.githubusercontent.com/62153141/139486556-92c9f01d-e4d6-4227-8a8a-eeab8cd23dd1.png)

The pop up letter on the home page feels a bit strange for a landing, but I do think it makes sense on the Overview page and possibly also the About the Plan page. Still need to add links to display the pop up on the necessary pages.

**Comment by theryankelly** [comment]
On Chrome:
![image](https://user-images.githubusercontent.com/2421382/142914944-3f507ab8-bb0e-4138-989a-6183b183bc6e.png)

On Edge:
![image](https://user-images.githubusercontent.com/2421382/142915014-2b4ba541-766b-408c-8f16-7ac8c599b0f0.png)

I am able to bypass reading the letter and scroll to the rest of the site. I would expect this letter to overlay the full site, not just the header. The user would not be able to scroll until they close the letter.

**Comment by theryankelly** [comment]
No scroll and "X" to close look good. Just need more distinction between letter and page. Need to overlap more beyond the green top section into the next. Maybe a darker overlay and drop shadow to highlight it's a pop-up.

**Comment by theryankelly** [comment]
Current styling in Chrome/Windows: 
![image](https://user-images.githubusercontent.com/2421382/143309294-c6719f26-eacb-4fe0-bd58-09857ee2d73c.png)

realizing the user will have to close out the letter every time they visit. Will revisit and test further next week.

**Comment by theryankelly** [comment]
From Eric: _Letter from ED: it appears abruptly. Is there a way to "ease" into it?_

**Comment by theryankelly** [comment]
Notes from 12/13 meeting 

- [ ] @trust-kimberly to add fade transition on load

**Comment by theryankelly** [comment]
Fade is slow to appear. I tried to scroll before appeared. However, I think it is good enough for launch. Closing issue
