### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#538]
Current About Page is Process Details Page (Attic as a nickname) https://metrocommon.mapc.org/process-details

Decisions Needed:
- [x] Process Report to be included on about page? **Yes**
- [x] Update current Process timeline slides or new?Keep? **Keep and update to one slide: #587** 
- [x] Embed or Links to https://mc2050.pory.app here or separate page? **Yes, will add to box with link**
- [ ] Remove current links on process details?
- [ ] What are we linking out to from this page? What are in boxes?

**Comment by theryankelly** [comment]
Given the current state of the About/ Process Details template, we will not be able to directly edit the section. Will need to be content we get right in word and @trust-kimberly adds in. Kimberly, let me know if that is accurate.

**Comment by trust-kimberly** [comment]
> Given the current state of the About/ Process Details template, we will not be able to directly edit the section. Will need to be content we get right in word and @trust-kimberly adds in. Kimberly, let me know if that is accurate.

This is accurate, so when changes to the word doc are finalized, send me a message please.

**Comment by theryankelly** [comment]
#665

**Comment by theryankelly** [comment]
**Nice to have** 
Add two columns to the acknowledgments section to cut down on height.

**Comment by theryankelly** [comment]
MC Events box  is currently linking to HH Action Brief https://staging.metrocommon.mapc.org/assets/MC2050_Homes_for_Everyone_Brief-690bdc3dc52307832a68d088199a3e95500a216340e18257dfeebb5994cd6708.pdf

![image](https://user-images.githubusercontent.com/2421382/146412015-559dcb9e-d97e-42cb-95ce-080d7f056e38.png)

**Comment by theryankelly** [comment]
Two columns looks good for scenario section ![image](https://user-images.githubusercontent.com/2421382/146412816-ed519adf-57c1-44c5-9a3c-3db9b0d0b5f7.png)

Can same be done for staff a few names get dropped to next line
![image](https://user-images.githubusercontent.com/2421382/146412920-2b6bee5c-0a5b-4389-a4b0-21b508de8e57.png)

**Comment by trust-kimberly** [comment]
Adjusted the width of the staff acknowledgements. I intentionally kept it single column versus two since each line was much longer than the single name lines of other sections. 

<img width="650" alt="Screen Shot 2021-12-16 at 1 55 16 PM" src="https://user-images.githubusercontent.com/62153141/146432217-cd73d4ce-4076-4446-9c21-3bcee272a507.png">
