### ISSUE TITLE
Staging Down, 500 Error

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#541]
**Describe the bug**
https://staging.metrocommon.mapc.org/ is currently down when tested on 9/10. 

![image](https://user-images.githubusercontent.com/2421382/132907483-43c32aad-f638-4fec-8b4f-ed6451ecfcd8.png)
![image](https://user-images.githubusercontent.com/2421382/132907570-dd659dc4-61c6-4bd2-8412-8b1b788615b7.png)

**Comment by TarinAComer** [comment]
rebooted the instance in AWS and staging is back up and running.
