### ISSUE TITLE
Identify formatting for recommendation/action url

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#544]
Need to share with SI and Comms teams what formatting options we have for policy page URLs going forward. So they can appropriately name and identify them during the transfer process.

**Comment by theryankelly** [comment]
Will need to create two new templates for Action Area Landing Pages and Policy Remonendation Pages. The Action Area Landing Pages will live within the Action Area Home Page, which itself does not need to be a template. Policy Recommendations Home Page is not needed will direct to Action Area Home Page

Action Area Home Page: metrocommon.mapc.org/actions
Action Area Landing Pages: metrocommon.mapc.org/actions/ `{Area-Area-Short-Name}`
Policy Recommendations: metrocommon.mapc.org/policy-recomendations/ `{Policy-Short-Name}`

`{Area-Area-Short-Name}` and `{Policy-Short-Name}` should be recognizable and probably shorter than current titles.
- Only ASCII characters 
- Keep lowercase
- Avoid any special characters like (:, /,&)
- Avoid underscores (_) use (-) to separate out words for better SEO.

**Comment by theryankelly** [comment]
@elisemaeharmon

**Comment by elisemaeharmon** [comment]
@theryankelly: Got from Karen and saved here: https://mapc365.sharepoint.com/:w:/s/CommunicationsTeam/EbQAB7UMKJNJv3ZEv_QBxBIB5fso-5ZnGqLMkooop5QVTQ?e=wwcnH1
