### ISSUE TITLE
Choose short names for recommendation/actions/topics

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#546]
SI and Comms choosing names

**Comment by elisemaeharmon** [comment]
@theryankelly Slugs from Karen are here: https://mapc365.sharepoint.com/:w:/s/CommunicationsTeam/EbQAB7UMKJNJv3ZEv_QBxBIB5fso-5ZnGqLMkooop5QVTQ?e=wYhgxk

**Comment by theryankelly** [comment]
While AA slugs have been implemented the Policy Recommendation URL will not be able to match without additional effort. Were able to get the Policy Recommendations to follow this convention: /announcements/recommendations/[ID #]

**Comment by theryankelly** [comment]
Closing issues, names will be /announcements/recommendations/[ID #]
