### ISSUE TITLE
Copy for AA Cards

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#568]
Copy needed for the 5 Action Area cards that will be displayed throughout the site. Related #526

The current design has Lorum Ipsum of close to two sentences and about 20 words. Will need a similar amount of descriptive copy for each of the AA's.

- [x] Inclusive Growth and Mobility
- [x] Homes for All
- [x] Climate Mitigation & Resiliency
- [x] Dynamic and Representative Government
- [x] Equity of Wealth and Health

![125674047-beb1f0a0-22e4-479b-9d3d-68f7fc00e24f](https://user-images.githubusercontent.com/2421382/135627098-95588815-28d7-4477-a5c6-6f5fb8e0f3ca.png)

**Comment by elisemaeharmon** [comment]
@theryankelly sent to Karen!

**Comment by elisemaeharmon** [comment]
@theryankelly Received from Karen! 

**Climate Change Adaptation & Mitigation**   
Climate change is already altering our lives, and this will only intensify. How can we mitigate climate change and adapt to its effects now, to be better off by 2050? 

**Dynamic and Representative Government**  
Greater Boston has a long, proud history of local control. But some challenges – like housing and climate – know no borders. How do our municipalities become more effective – and more inclusive? 

**Equity of Wealth and Health** 
Disparities in health and wealth associated with race are not unique to Greater Boston, but they harm everyone. How do we close and redress these gaps – at a structural level? 

**Homes for Everyone** 
Greater Boston’s housing crisis devastates the cost-burdened, hurts the region’s quality of life, and weakens its economic competitiveness. How do we create more places to live, and protect against displacement? 

**Inclusive Growth & Mobility** 
The ways we get around in Greater Boston – and where and how we grow – has profound effects. How do we manage land use and transportation for the benefit of all?

**Comment by theryankelly** [comment]
Current Staging:
![image](https://user-images.githubusercontent.com/2421382/142914349-ccbbaa67-afe8-4b1c-b967-e0d222677405.png)

The text looks good. Closing this issue.
