### ISSUE TITLE
Action Areas Pages Side Bar

### ISSUE THREAD

**Issue by TarinAComer** [MAPC/digitalhub#579]
**Describe the feature. What should a user be able to do?**

<img width="295" alt="Screen Shot 2021-10-12 at 2 19 59 PM" src="https://user-images.githubusercontent.com/12685178/137008710-12785eba-efc8-4b44-a292-899a5f963c06.png">

**Why do we need this feature?**
We need to have the side bar to link out to various features related to this action area

**Comment by theryankelly** [comment]
I think the Side Bar design looks good. Just need the final AA art and links #585  and #559

**Comment by theryankelly** [comment]
Closing this issue as #585 and #559 remain to be linked, but component created
