### ISSUE TITLE
Action Area Pages Recommendation Links Section

### ISSUE THREAD

**Issue by TarinAComer** [MAPC/digitalhub#580]
**Describe the feature. What should a user be able to do?**
The section that links out to various recommendations using uniformly sized links with images need to be added to individual action area pages.

<img width="209" alt="Screen Shot 2021-10-12 at 2 22 46 PM" src="https://user-images.githubusercontent.com/12685178/137009512-571904e4-97db-46d6-b164-7fc052a2dc33.png">

**Why do we need this feature?**
It is part of the design

**Comment by theryankelly** [comment]
Current Staging:
![image](https://user-images.githubusercontent.com/2421382/142914629-dc0ee585-4ea3-4830-bec7-7a113f3f08eb.png)

Section of AA page that links out to Policy Recommendations looks good. Links appear to be associated with the correct pages. Closing this issue.
