### ISSUE TITLE
Set up analytics events for tracking downloads and pageviews

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#582]

**Comment by theryankelly** [comment]
@trust-kimberly can you share a screenshot of which downloads are tracked? Can we confirm this will work when moved to production or set a reminder to check?

**Comment by trust-kimberly** [comment]
The downloads being tracked are each of the 5 AA pdf briefs linked in the sidebar, and 20 recommendation individual pdf's linked in the header, so 25 total.

![Screen Shot 2021-12-13 at 6 01 30 PM](https://user-images.githubusercontent.com/62153141/145902940-11b56031-b616-4170-9e96-5e31a1f2bec3.png)
(AA individual landing)
![Screen Shot 2021-12-13 at 6 01 38 PM](https://user-images.githubusercontent.com/62153141/145902828-d46115ae-29a8-4db6-a8c0-8d9fe707d2fb.png)
(Recommendation page)

In Google Analytics, we can see which pdf's have been downloaded (the majority of which were during my testing when setting up events and tracking). We can't yet see all 25 pdf's tracked until they've each been downloaded at least once to run the script that makes a call to GA.

![Screen Shot 2021-12-13 at 5 49 30 PM](https://user-images.githubusercontent.com/62153141/145903026-ae6fdeee-fd92-4f82-a6ac-36468d243993.png)

For AA sidebars, the script was hardcoded:

![Screen Shot 2021-12-13 at 5 51 24 PM](https://user-images.githubusercontent.com/62153141/145903925-5ca0c2e6-1976-4fd2-9f29-7f1040a9b97b.png)

and for recommendation pages, the script was added via CMS:

<img width="1052" alt="Screen Shot 2021-12-13 at 5 52 06 PM" src="https://user-images.githubusercontent.com/62153141/145903968-443cef2f-be43-48cd-af48-5fd7637650c0.png">

Given this setup, it would be best to set a reminder to test again once pushed to production!

**Comment by theryankelly** [comment]
Closing issues with tracking enabled as described above
