### ISSUE TITLE
Header Overlap on Policy Recommendations

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#623]
Chrome header overlaps on Policy Recommendation pages
![header overlap on rec](https://user-images.githubusercontent.com/2421382/142917913-243b6827-7509-4e52-8c35-fdc032d67b6c.png)

Edge as well:
![image](https://user-images.githubusercontent.com/2421382/142918019-4b4b7662-648a-41b5-a260-0e149a1ea8d9.png)

**Comment by trust-kimberly** [comment]
![Screen Shot 2021-11-22 at 3 59 22 PM](https://user-images.githubusercontent.com/62153141/142934532-802dad8f-7f67-4229-90ac-47fc43b63e17.png)

Recommendations headers and buttons were fixed and deployed to staging. Confirmed that the overlap no longer happens in Chrome or Safari, but did not yet try Edge. Moving this issue for review.

**Comment by theryankelly** [comment]
Here is Edge. All look good. Closing this issue.
![image](https://user-images.githubusercontent.com/2421382/143308319-f64c999d-e728-4141-91c9-ba5047626aa7.png)
