### ISSUE TITLE
Link to research currently to events

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#624]
Disable/Hide event link?

**Comment by trust-kimberly** [comment]
Screenshot from development. Could fill with one or two more linked research reports?

![Screen Shot 2021-12-10 at 11 34 08 AM](https://user-images.githubusercontent.com/62153141/145608980-c5e8362d-0cde-4211-b8d0-8bbfe0f3cb34.png)

**Comment by theryankelly** [comment]
Rethink Suburban Strip won't be out till Jan 11. Remove until then?

**Comment by theryankelly** [comment]
For launch today let's go wih the removal of Rethink Suburban Strip as we don't have a placeholder ready.
