### ISSUE TITLE
Height and width bars on hero text

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#626]
![bars](https://user-images.githubusercontent.com/2421382/142918286-3e0e5f48-72da-4309-a372-a23e86ef5a48.png)

**Comment by theryankelly** [comment]
So heigh bars are gone on hero text and pillboxes. However, the lateral scroll of pillboxes is also gone. Can't get to climate AA.

Chrome, Windows:
![image](https://user-images.githubusercontent.com/2421382/143308524-5e3a0206-6583-4bd5-87c9-f3154e01c335.png)

**Comment by trust-kimberly** [comment]
So strange - I could still horizontally scroll in Chrome on mac, so thought it could be an issue with Citrix. Will circle back to this.

**Comment by theryankelly** [comment]
Note from Eric: Landing page: AA "cards" is there a way to center it so you can immediately see there are 5 AAs?

**Comment by theryankelly** [comment]
New copy in #553 will affect height need in hero.

**Comment by theryankelly** [comment]
Closing issue as new (shorter) hero copy was added and scroll bar removed.

![image](https://user-images.githubusercontent.com/2421382/145896758-ed834a03-15e8-497f-bfa9-5d36bca9bf63.png)
