### ISSUE TITLE
Future Uncertainties Background Images

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#633]
Moving this issue from the Scenario Board to this project board.

Need to select backgrounds of high resolution for the Future Uncertainties slideshows. One option is to choose images to replace current low-resolution photos. The second option would be to create and use a pattern. A pattern might help the images in the slideshow pop more and not contrast as much with the background.

Current look
![image](https://user-images.githubusercontent.com/2421382/143277371-febb21f2-c555-424e-b141-d0e49eba668d.png)
![image](https://user-images.githubusercontent.com/2421382/143277402-e77ee5c6-9843-4e09-9dcd-22ca162d70cf.png)
![image](https://user-images.githubusercontent.com/2421382/143277462-84ea803e-9f22-4b75-950f-d9cef9d101e8.png)
![image](https://user-images.githubusercontent.com/2421382/143277488-67110e9b-3df6-4cf0-be3c-82f832473caf.png)

**Comment by theryankelly** [comment]
@elisemaeharmon @sashaparodi what images or pattern do you want to use?

**Comment by trust-kimberly** [comment]
With the subtler MC branding icons background, the decks are looking much more legible while still prominent. Changes are live.

<img width="1420" alt="Screen Shot 2021-12-13 at 5 54 51 PM" src="https://user-images.githubusercontent.com/62153141/145902322-96b23a20-11ad-4d17-bb1b-924f82fb7193.png">

**Comment by theryankelly** [comment]
Closing issues as background on staging look as expected for launch 
![image](https://user-images.githubusercontent.com/2421382/146047225-8a7fee90-013c-49fd-a63d-7453b15a140b.png)
