### ISSUE TITLE
Learn more about MAPC's Future of Work research - link doesn't work. Uncertain Future > A changing economy > end of slide show. Seems like none of links at the ends of the slideshows are connected.

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#642]

**Comment by theryankelly** [comment]
@japartridge is this a link on metrocommon.mapc.org that is not working?

**Comment by japartridge** [comment]
No, I was exploring the Digital Hub staging site (I'm in that channel, so I saw your message).

Jessie Partridge Guerrero (she/her)
Research Manager
Metropolitan Area Planning Council
Cell: 781-526-7997

Data Services is hiring for a Socioeconomic Analyst II<https://www.governmentjobs.com/careers/mapc/jobs/3259637/socioeconomic-analyst-ii>
________________________________

**Comment by theryankelly** [comment]
Trying to track down the slide show you are referencing. Not one of the Scenario / Future Uncertainties slides (https://mapc.github.io/scenario-planning/)? 

Is there a slide show on staging referencing this work?
https://www.mapc.org/planning101/the-future-of-work-data-and-policies-to-shape-greater-bostons-recovery/

**Comment by japartridge** [comment]
Yes, it's those slides in the future uncertainties section, here's a screenshot of one (the here link doesn't work for me):

[cid:7b67e0b7-7a09-4925-9885-ac5be2189fe8]

Jessie Partridge Guerrero (she/her)
Research Manager
Metropolitan Area Planning Council
Cell: 781-526-7997

Data Services is hiring for a Socioeconomic Analyst II<https://www.governmentjobs.com/careers/mapc/jobs/3259637/socioeconomic-analyst-ii>
________________________________

**Comment by theryankelly** [comment]
Closing as links in slideshow now function as expected. 
![image](https://user-images.githubusercontent.com/2421382/146047076-24004738-6e4d-43ba-b844-f7cb3a18ca17.png)
