### ISSUE TITLE
Add values or the racial equity statement to Overview page

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#652]
Both are located here:
https://mapc.sharefile.com/share/view/sa94f8e0808c8476eb1714f097d687928/fo307db4-0af5-4d46-8455-f66f1e02fb96 
and 
https://mapc.sharefile.com/share/view/sa94f8e0808c8476eb1714f097d687928/fo307db4-0af5-4d46-8455-f66f1e02fb96 correct?

**Comment by trust-kimberly** [comment]
Currently we have the values and expanded racial equity statement on the About the Plan page, but we also want to add it to the Overview page? Or move the content?

**Comment by theryankelly** [comment]
Confirmed at 12/13 meeting will move the section from About to Overview as is with equity popup included. About will still have pdf for download #538
