### ISSUE TITLE
Footnote hidden

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#657]
Footnotes are not currently prominent on the recommendation page. Should also link/jump down to notes.

![Footnote hidden](https://user-images.githubusercontent.com/2421382/145636618-67c966d9-cc7e-40b0-a2dc-83a5b36a5fdd.png)

**Comment by trust-kimberly** [comment]
Re-styled inline footnotes to better highlight them, and all jump down to list of footnotes at bottom of page. 

<img width="641" alt="Screen Shot 2021-12-13 at 1 09 49 PM" src="https://user-images.githubusercontent.com/62153141/145865749-7ef0c112-5ed6-4a1e-8ae2-285ee232a38e.png">

**Comment by theryankelly** [comment]
Changes on staging look good. Footnotes are viable and links work. Closing the issue.
