### ISSUE TITLE
Remove menu from Future Uncertainties report

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#663]
The menu currently does not link to the refinery menu. Consider removing altogether

![image](https://user-images.githubusercontent.com/2421382/145865365-346992d0-4476-4909-a096-4a11fc758c89.png)

**Comment by trust-kimberly** [comment]
Removed the menu and "MetroCommon x 2050" links to digitalhub production.

**Comment by theryankelly** [comment]
Closing as menu was removed on staging. ![image](https://user-images.githubusercontent.com/2421382/146047316-e696bbf8-7f0e-4d18-ab63-1b8ab3313a4c.png)
