### ISSUE TITLE
Adjust Future Scenario Dynamic Gov Red Color

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#666]

**Comment by trust-kimberly** [comment]
Used the red with lower saturation that is used later in the deck.

![Screen Shot 2021-12-13 at 5 59 05 PM](https://user-images.githubusercontent.com/62153141/145902508-d23aa3a5-4ca6-4501-a007-8f37d11ac145.png)

**Comment by theryankelly** [comment]
Color adjustment looks good. Closing issue.
