### ISSUE TITLE
Production Site Review

### ISSUE THREAD

**Issue by trust-kimberly** [MAPC/digitalhub#685]
- [x] Recommendation header images (uploaded)

![Screen Shot 2021-12-20 at 9 56 01 AM](https://user-images.githubusercontent.com/62153141/146787398-52387dd5-28eb-4c39-8df0-e3417548c327.png)

- [x] Recommendations not showing in Find Out, related to missing images, but these two somehow pulled unrelated art images 

![Screen Shot 2021-12-20 at 10 06 31 AM](https://user-images.githubusercontent.com/62153141/146788716-5e23e5de-ddbc-4503-9f4d-684632f4f875.png)

- [x] Update Recommendation dates (bottom of page) in admin
- [x] Favicon
- [x] Overview page unavailable
- [x] Process Details needs to be renamed About the Plan with corresponding slug /about-the-plan
- [x] Merge and push outstanding PR's
- [x] Main menu needs reordering:
Home
Overview
Action Areas
Research & Tools
Goals
About the Plan
(#555 for details)

**Comment by TarinAComer** [comment]
- [ ] recommendation pdfs were all broken
- [ ] images were all broken

**Comment by theryankelly** [comment]
- [ ] Research section One Boxes need to be updated with new images and links, currently old production One Boxes.
- [ ] [Private Policy ](https://metrocommon.mapc.org/privacy-policy)in Footer does not work (did it before?) 
- [ ] About MAPC link in home page section should go to mapc.org/aboutus
